//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./news_types');
//HELPER FUNCTIONS AND STRUCTURES

GetNews_ping_args = function(args) {
};
GetNews_ping_args.prototype = {};
GetNews_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GetNews_ping_args.prototype.write = function(output) {
  output.writeStructBegin('GetNews_ping_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GetNews_ping_result = function(args) {
};
GetNews_ping_result.prototype = {};
GetNews_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GetNews_ping_result.prototype.write = function(output) {
  output.writeStructBegin('GetNews_ping_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GetNews_getTopNews_args = function(args) {
};
GetNews_getTopNews_args.prototype = {};
GetNews_getTopNews_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GetNews_getTopNews_args.prototype.write = function(output) {
  output.writeStructBegin('GetNews_getTopNews_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GetNews_getTopNews_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
GetNews_getTopNews_result.prototype = {};
GetNews_getTopNews_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new ttypes.News();
          elem6.read(input);
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GetNews_getTopNews_result.prototype.write = function(output) {
  output.writeStructBegin('GetNews_getTopNews_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GetNews_zip_args = function(args) {
};
GetNews_zip_args.prototype = {};
GetNews_zip_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GetNews_zip_args.prototype.write = function(output) {
  output.writeStructBegin('GetNews_zip_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GetNews_zip_result = function(args) {
};
GetNews_zip_result.prototype = {};
GetNews_zip_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GetNews_zip_result.prototype.write = function(output) {
  output.writeStructBegin('GetNews_zip_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GetNewsClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
GetNewsClient.prototype = {};
GetNewsClient.prototype.seqid = function() { return this._seqid; }
GetNewsClient.prototype.new_seqid = function() { return this._seqid += 1; }
GetNewsClient.prototype.ping = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ping();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ping();
  }
};

GetNewsClient.prototype.send_ping = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid());
  var args = new GetNews_ping_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

GetNewsClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new GetNews_ping_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
GetNewsClient.prototype.getTopNews = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getTopNews();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getTopNews();
  }
};

GetNewsClient.prototype.send_getTopNews = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getTopNews', Thrift.MessageType.CALL, this.seqid());
  var args = new GetNews_getTopNews_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

GetNewsClient.prototype.recv_getTopNews = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new GetNews_getTopNews_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getTopNews failed: unknown result');
};
GetNewsClient.prototype.zip = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_zip();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_zip();
  }
};

GetNewsClient.prototype.send_zip = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('zip', Thrift.MessageType.ONEWAY, this.seqid());
  var args = new GetNews_zip_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};
GetNewsProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
GetNewsProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

GetNewsProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new GetNews_ping_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ping.length === 0) {
    Q.fcall(this._handler.ping)
      .then(function(result) {
        var result = new GetNews_ping_result({success: result});
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new GetNews_ping_result(err);
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ping( function (err, result) {
      var result = new GetNews_ping_result((err != null ? err : {success: result}));
      output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

GetNewsProcessor.prototype.process_getTopNews = function(seqid, input, output) {
  var args = new GetNews_getTopNews_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getTopNews.length === 0) {
    Q.fcall(this._handler.getTopNews)
      .then(function(result) {
        var result = new GetNews_getTopNews_result({success: result});
        output.writeMessageBegin("getTopNews", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new GetNews_getTopNews_result(err);
        output.writeMessageBegin("getTopNews", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getTopNews( function (err, result) {
      var result = new GetNews_getTopNews_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getTopNews", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

GetNewsProcessor.prototype.process_zip = function(seqid, input, output) {
  var args = new GetNews_zip_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.zip()
}

